# Generated by Django 6.0.5 on 2026-05-16 04:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('supplier', models.CharField(choices=[('A', 'Supplier A'), ('B', 'Supplier B'), ('C', 'Supplier C')], max_length=1)),
                ('product_line', models.CharField(choices=[('Camisetas', 'Shirts'), ('Pantalones', 'Pants'), ('Zapatos', 'Shoes'), ('Accesorios', 'Accessories')], max_length=20)),
                ('status', models.CharField(choices=[('Programada', 'Scheduled'), ('En proceso', 'In Progress'), ('Entregada', 'Delivered'), ('Cancelada', 'Cancelled')], default='Programada', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status'], name='appointment_status_8fe9d7_idx'), models.Index(fields=['supplier'], name='appointment_supplie_74e826_idx'), models.Index(fields=['product_line'], name='appointment_product_13b7b2_idx'), models.Index(fields=['scheduled_at'], name='appointment_schedul_7069dc_idx'), models.Index(fields=['created_by'], name='appointment_created_4ebf5b_idx')],
            },
        ),
    ]
